### ISSUE TITLE
API resource {id} is not regustered on {uri}

### ISSUE THREAD

**Issue by paulalwin91** [microsoft/azure-devops-auth-samples#21] opened 2018-06-15 19:43 UTC
I am getting the error when i access build information in my tfs account. 

API resource {id} is not regustered on {uri}

Do i need to reguster somthing?

**Comment by justmarks** [comment] 2018-09-04 15:09
@paulalwin91 can you be more specific about what API you're calling? I'm not able to reproduce this

**Comment by anydot** [comment] 2021-04-23 14:29
closing due to old age

**Closed by anydot** 2021-04-23 14:29 UTC
